### ISSUE TITLE
Make an application server 

### ISSUE THREAD

**Issue by tarq2000** [chirpstack/chirpstack-docker#104]
How can we Generate MQTT certificate and also make The MQTT integration forwards events to a MQTT broker.
when I push the "Generate certificate" I have this error:
Read gateway ca_cert: No such file or directory (os error 2)

**Comment by tarq2000** [comment]
thank you for your help, But I have this problem with this docs :
In the chirpstack.toml I can't find the [gateway] section and also [integration.mqtt.client] section

**Comment by brocaar** [comment]
https://www.chirpstack.io/docs/chirpstack/configuration.html#example-chirpstacktoml-configuration
