### ISSUE TITLE
problem with CA certificate

### ISSUE THREAD

**Issue by tarq2000** [chirpstack/chirpstack-docker#105]
I have this two code for CA certificate in file region_eu868.toml 
       ca_cert="chirpstack-docker/certs/ca/ca.pem"
        ca_key="chirpstack-docker/certs/ca/ca-key.pem" 
The problem is, When I run the docker I have this error : 
chirpstack-1                              | Error: New MQTT gateway backend error
chirpstack-1                              |
chirpstack-1                              | Caused by:
chirpstack-1                              |     0: Open CA certificate
chirpstack-1                              |     1: No such file or directory (os error 2)
chirpstack-1 exited with code 1

**Comment by brocaar** [comment]
You need to make sure that `chirpstack-docker` is available **within** the container, the current volumes can be found here:

https://github.com/chirpstack/chirpstack-docker/blob/master/docker-compose.yml#L8
