### ISSUE TITLE
Support MA869 and KZ865

### ISSUE THREAD

**Issue by xiaoye-x** [chirpstack/chirpstack-docker#107]
Is it possible to add the MA869 and KZ865 profiles, I can't add the toml profile directly because once it runs it prompts that it can't change the common_name to MA869

**Comment by brocaar** [comment]
This is not the correct repo to request this, https://github.com/chirpstack/chirpstack/ is.

However, these regions are not (yet) specified. Please see: https://resources.lora-alliance.org/technical-specifications/rp002-1-0-4-regional-parameters
