### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by darkfader** [chirpstack/chirpstack-docker#32]
Add some example showing combinations of single/multiple postgreqsl and redis servers.
Can NS and AS have their own set?
How to do multi-region? Can it be done on 1 forwarder UDP port?
I have no clue what can or needs to be separated.
I'm trying to add a network server in a new set of databases, NS and AS in my currently docker-compose file, but I get an error that the object already exists...

**Comment by brocaar** [comment]
I think issue is no longer relevant anymore. I've update the Docker example to ChirpStack v4, which supports multi-region out-of-the-box. The readme describes how to connect the ChirpStack Gateway Bridge to the different regions.
