### ISSUE TITLE
upgrade postgres

### ISSUE THREAD

**Issue by gilloud** [chirpstack/chirpstack-docker#54]
Postgres 9.6 is not supported anymore, no security fix will be provided by the core team.
An upgrade can be purposed in the compose files : 

- https://github.com/brocaar/chirpstack-docker/blob/master/docker-compose.yml#L31
- https://github.com/brocaar/chirpstack-docker/blob/master/docker-compose-env.yml#L39

Regards,

**Comment by luis-moral** [comment]
As bonus, using `postgres:10.20-alpine` (oldest supported version) the initialization scripts will work in windows and I guess in mac probably too.

Issue fixed -> https://forum.chirpstack.io/t/chirpstack-docker-image-cant-connect-to-postgres/10183/4

**Comment by brocaar** [comment]
PostgreSQL has been updated :)
