### ISSUE TITLE
First start fails to create chirpstack user and database on postgres container.

### ISSUE THREAD

**Issue by enishyseni** [chirpstack/chirpstack-docker#60]
Error: Setup PostgreSQL connection pool error

Caused by:

    timed out waiting for connection: FATAL:  password authentication failed for user "chirpstack"

**Comment by wong-hao** [comment]
The same as you sir. Any progress?

**Comment by brocaar** [comment]
Could you try the following sequence of commands (please note that this is going to remove some volumes, before you execute these commands on a production environment, please be aware what each command does or you might accidentally delete data that you do not want to delete):

```bash
docker-compose stop
docker-compose rm -f
docker volume rm chirpstack-docker_postgresqldata
docker volume rm chirpstack-docker_redisdata
```

In case you have installed ChirpStack before using this repository, it will store the databases in a Docker volume. Even if you remove the containers and images, the volumes are retained. Thus the next time when you install ChirpStack, the old database is still there.

After the above, a `docker-compose up` will result in a clean install and the databases will be initialized.

**Comment by dloftus98** [comment]
> 

I had to set the execute bit on the scripts in initdb as well as set the POSTGRES_USER=postgres:

`$ POSTGRES_USER=postgres docker-compose up`
