### ISSUE TITLE
Runing chirpstack on K8s, always crash

### ISSUE THREAD

**Issue by ulfaric** [chirpstack/chirpstack-docker#62]
Hi,

I am trying to run chirpstack on K8s. So far I have got every other components successfully running, but only chirpstack/chirpstack:4.0.0 always crashes.

My yaml file is attached, really appreciate it if you could help!

[chirpstack.zip](https://github.com/chirpstack/chirpstack-docker/files/9584085/chirpstack.zip)

**Comment by brocaar** [comment]
Please check the logs, probably it is a misconfiguration. I'm closing this issue, as it is not related to this repository.
