### ISSUE TITLE
sudo not available

### ISSUE THREAD

**Issue by AndreasW79** [chirpstack/chirpstack-docker#65]
Hi,
first - thanks again for this great piece of software.
Second, i tried to add the TTN device repo into the docker container but cant sudo any command, neither i have found the root password for the containers? Did i miss something or what will be the best way to import the TTN device repo into an dockerized environment?

Thanks in advance.

**Comment by brocaar** [comment]
Did you see this `make` command?

https://github.com/chirpstack/chirpstack-docker/blob/master/Makefile#L1

Note that it does not require `sudo`.

**Comment by AndreasW79** [comment]
No maybe i missed that, will try it in the next days - looks like a solution, i will close this.
Thank you for the support.
