### ISSUE TITLE
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by gougakos** [chirpstack/chirpstack-docker#70]
Hi when installing the docker image on a rpi2 the rest api is failing to start with the error

chirpstack-docker $ docker-compose up
Pulling chirpstack-rest-api (chirpstack/chirpstack-rest-api:4.0.4)...
4.0.4: Pulling from chirpstack/chirpstack-rest-api
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

**Comment by brocaar** [comment]
Could you try again with the latest version of this repository? I believe this is fixed by: https://github.com/chirpstack/chirpstack-rest-api/commit/c4b57ec092c7075532d0e9f8c00a0c758666f4fc.

**Comment by gougakos** [comment]
Hi, thanks for the prompt fix. Tested already and confirm it works!
