### ISSUE TITLE
Issue with HTTP integration to multiple endpoints

### ISSUE THREAD

**Issue by thanospan** [chirpstack/chirpstack-docker#80]
**Description**
The HTTP integration accepts multiple endpoints as a comma separated list. If posting to an endpoint fails, no request is sent to the remaining endpoints.

**Steps to reproduce**
Create an HTTP integration with two endpoints where the first is invalid (e.g., wrong IP, port, hostname). No data is received by the second endpoint.

Tested with the latest Docker images (v4) using commit `a281b17`.

**Comment by brocaar** [comment]
Thanks for reporting, I'm looking into this. Next time please report this issue at: https://github.com/chirpstack/chirpstack/.

This issue is related to the ChirpStack source, not to the Docker configuration example.
