### ISSUE TITLE
Failed to set MQTT backend protocol to JSON

### ISSUE THREAD

**Issue by amoat7** [chirpstack/chirpstack-docker#81]
I'm using a RAK7289 gateway. So far, I've been successful in connecting the gateway to chirpstack and receiving messages in my MQTT broker when i use the protobuf protocol. When i change the protocol to JSON however in my RAK7289 gateway, chirpstack is unable to parse it even after I set `json=true` in  my regional config file `region_au915_0.toml`. It still defaults to fault and I keep getting this error

`INFO chirpstack::gateway::backend::mqtt: Message received from gateway region_config_id="au915_0" topic="au915_0/gateway/********/event/stats" qos=1 json=false`

How do i resolve this?

**Comment by robsonos** [comment]
I am having a similar problem but with the RAK7248 and RAK7249

**Comment by brocaar** [comment]
> When i change the protocol to JSON however in my RAK7289 gateway, chirpstack is unable to parse it

I'm going to close this issue, as it is not related to the Docker Compose example. Could you please create an issue in the ChirpStack repository with the steps needed to reproduce the issue?

Please also include version numbers + if you are using the Gateway Bridge or MQTT Forwarder.

Thanks!
