### ISSUE TITLE
Import TTN device repository FAIL

### ISSUE THREAD

**Issue by j0hu** [chirpstack/chirpstack-docker#85]
Hello, I have installed the ChirpStack v4 as Docker with the actual docker-compose.yaml (unchanged).

The Stack starts completly smooth, the WebIf is reachable - all is fine.

But when I'm trying to import the TTN device repository with the following command:

`make import-lorawan-devices`

I get this error message:

```
admin@docker-iot:/mnt/nvme-data/docker/chirpstack$ sudo make import-lorawan-devices
docker-compose run --rm --entrypoint bash --user root chirpstack -c '\
        apt-get update && \
        apt-get install -y make git && \
        git clone https://github.com/brocaar/lorawan-devices /tmp/lorawan-devices && \
        chirpstack -c /etc/chirpstack import-legacy-lorawan-devices-repository -d /tmp/lorawan-devices'
[+] Creating 3/0
 ✔ Container chirpstack-redis-1      Running                                                                                                                                                                                            0.0s
 ✔ Container chirpstack-mosquitto-1  Running                                                                                                                                                                                            0.0s
 ✔ Container chirpstack-postgres-1   Running                                                                                                                                                                                            0.0s
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown
make: *** [Makefile:2: import-lorawan-devices] Error 1
```

For testing I try to start the bash of container/service "chirpstack" manually with:

`docker exec -it chirpstack-chirpstack-1 bash` or
`docker-compose exec -it chirpstack bash`

and get the same error:

`OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown`

**Versions**
Docker: 24.0.2
Docker-Compose (standalone): v2.19.0
OS: Ubuntu Server 23.04 (as an Proxmox LXC container)

Is this a bug or a feature? Or i'm simply doing something wrong?

Greetings, j0hu

**Comment by nconder** [comment]
Ill second that issue.

**Comment by brocaar** [comment]
Thanks for reporting :+1: The above commit fixes the issue.

**Comment by nconder** [comment]
> Thanks for reporting 👍 The above commit fixes the issue.

Working good thanks!
