### ISSUE TITLE
how to change the username and password of the mqtt broker ？

### ISSUE THREAD

**Issue by zhangyyhh** [chirpstack/chirpstack-docker#87]
Hello, I am an engineer from China. May I ask how to change the username and password of the mqtt broker after installing the chirpstack server using Docker

**Comment by brocaar** [comment]
Please find all ChirpStack configuration files here:
https://github.com/chirpstack/chirpstack-docker/tree/master/configuration

To configure Mosquitto with username / password authentication, please see:

* https://mosquitto.org/documentation/authentication-methods/
* http://www.steves-internet-guide.com/mqtt-username-password-example/

**Comment by zhangyyhh** [comment]
I am using the chipstack v3 version.
https://github.com/chirpstack/chirpstack-docker/tree/v3 
 May I know which configuration file I should modify? I cannot find a way to modify it. Could you please provide assistance

**Comment by zhangyyhh** [comment]
I edit chirpstack-gateway-bridge.toml as:
[integration.mqtt.auth.generic]
servers=["tcp://mosquitto:1883"]
username="inspur"
password="cxyjs123@"

and i edit mosquitto.conf as 
listener 1883
allow_anonymous false

but those opration all faild
