### ISSUE TITLE
Can we set for chirpstack server and Lorawan run without Internet?

### ISSUE THREAD

**Issue by khoa21214475** [chirpstack/chirpstack-docker#90]
Can you guide me on how to set up Lorawan to run a local network without Internet?
Thanks a lot!

**Comment by trivialkettle** [comment]
What exactly is your issue?
Just start the docker:
```
docker compose up -d
```
and access ChirpStack at
```
http://localhost:8080
```

**Comment by brocaar** [comment]
I'm closing this issue as there is nothing that prevents you to run ChirpStack without internet connection
